# Generated by Django 5.1.5 on 2025-04-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='aes_nonce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='aes_tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='encrypted_symmetric_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
