# Generated by Django 5.1.5 on 2025-04-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_aes_nonce_message_aes_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_kyte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
