# Generated by Django 5.1.5 on 2025-05-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_user_private_kyte"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ecdh_signature",
            field=models.TextField(blank=True, null=True),
        ),
    ]
