# Generated by Django 5.1.5 on 2025-05-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
