# Generated by Django 5.1.5 on 2025-06-03 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_message_timestamp_message_msg_recv_time_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='private_kyte',
        ),
    ]
