# Generated by Django 5.1.5 on 2025-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_user_groups_alter_user_user_permissions_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signing_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
