# Generated by Django 5.1.5 on 2025-06-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_user_signing_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encrypted_symmetric_key_for_sender',
            field=models.TextField(blank=True, help_text='AES key wrapped for sender (added in migration).', null=True),
        ),
    ]
