# Generated by Django 5.1.5 on 2025-06-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_message_encrypted_symmetric_key_for_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encrypted_symmetric_key_for_sender',
        ),
    ]
