# Generated by Django 5.1.5 on 2025-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_remove_message_encrypted_symmetric_key_for_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender_encrypted_symmetric_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
